### ISSUE TITLE
Refresh token support?

### ISSUE THREAD

**Issue by btrepp** [lastlogin-io/obligator#28]
Is it by design or not implemented that refresh tokens aren't implemented?. I see a security.md file that states they aren't implemented, but unsure if it's more a TODO, or would conflict with the stateless nature.

From #27 I was able to get lastlogin.io working with kubectl, however the one UX pain point is it seems the id_token lasts 10 minutes.
This means I am constantly logging back in :). It seems the kubectl plugin might support getting refresh tokens without the interactivity, but as obligator doesn't return them, I think it has to go for a full authorisation flow when the token expires.

https://github.com/lastlogin-io/obligator/blob/8fc6dd1b1c5201145d10486ca94d548480d8a607/docker/security.md?plain=1#L33

**Comment by anderspitman** [comment]
Hi @btrepp, glad you're finding this useful!

Technically, I can think of a couple ways to improve this. Policy and security is where it gets tricky.

Conceptually what LastLogin is asserting is X user controlled Y email address and Z time. So currently the tokens don't live much beyond "Z time". See [this link](https://stackoverflow.com/questions/25686484/what-is-intent-of-id-token-expiry-time-in-openid-connect) for me info.

My understanding is kubectl should be managing its own session once LastLogin has asserted an identity. But you're saying it keeps checking the ID token beyond the initial flow?

**Comment by btrepp** [comment]
I will do some testing and get some logs.

I suspect what kubectl is doing is getting the token and storing it locally, passing onto the API when needed. If there is a refresh token i *think* it calls that endpoint transparently when expired.

However without a refresh token, it uses the token it has until it expires, then requests a new one. 

I suspect lastlogin really wants to just provide that you own an email token, but kubectl is expecting the oidc service to provide more of that 'session' capability, as it's probably not minting it's own tokens to pass to the kubeapi, but just storing and passing them on

I very well might have cobbled these things together in some sort of duct tape and twigs situation that isn't what anyone initially intended :)

**Comment by btrepp** [comment]
I will do some testing and get some logs.

I suspect what kubectl is doing is getting the token and storing it locally, passing onto the API when needed. If there is a refresh token i *think* it calls that endpoint transparently when expired.

However without a refresh token, it uses the token it has until it expires, then requests a new one. 

I suspect lastlogin really wants to just provide that you own an email token, but kubectl is expecting the oidc service to provide more of that 'session' capability, as it's probably not minting it's own tokens to pass to the kubeapi, but just storing and passing them on

I very well might have cobbled these things together in some sort of duct tape and twigs situation that isn't what anyone initially intended :)

Update: Looks like kubernetes only wants to use the id token.

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

So I think the cli will refresh the id token if it has the endpoints, but without them, I assume it expires and triggers the full flow

**Comment by anderspitman** [comment]
Ok, refreshing ID tokens is definitely supported by the spec: https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse

I think they're might be a way to do it while preserving obligator's highly stateless architecture, using relatively short-lived refresh tokens with rotation.

The main problem I see currently is that as a free service LastLogin expects to only handle human login requests. Login is relatively rare and LastLogin should be able to handle a high number of users inexpensively. If we start supporting automated refresh, it could greatly increase the load. Might not be a problem in the short term.

That said, I'm not sure it's worth the added complexity, because I don't think there's a big difference security-wise between using refresh tokens, and simply setting longer-lived ID tokens.

Do you know how long you would need ID tokens to last for in order for it to not be annoying for your use case?

**Comment by btrepp** [comment]
So I was probably hitting regularly until I figured out what was going on
:).

For my use cases 1 hour would be plenty.
I think from a load perspective, perhaps it might be good to have some sort
of rate limiting anyway, protection from malfunctioning clients is probably
good and reasonable on what is a free service.

My other thoughts at the moment, is potentially for this use case, I should
run Dex infront of last login.

Kubectl -> Dex -> obligator -> Google/whatever.

This hopefully should have the advantage that Dex might handle the
refreshes (on something I host) but reach out to say obligatory/lastlogin
rarely, eg when I needs to figure out a user.

Dex seems to be able to upstream to another host, so that is good. Ideally
it would support anonymous Auth as well. I will give it a play.

https://dexidp.io/docs/connectors/oidc/

There could also be something there around doing that with obligator, so
retry tokens is something the end user apps should do, but the core last
login server doesn't for load.

Honestly the main reason I was using lastlogin.io. Is it was just so
fantastically easy, so you don't have to do the as much oidc pain when
hosting small apps. I've run authentik and keycloak and they were exercises
in frustration, where as obligator sorta just did one thing and did it
super well :). So adding a little bit of self hosting back is not so much a
problem :)

**Comment by anderspitman** [comment]
I'd hate for you to have to run an entire other service if it's just a small change on my end. I don't see any reason ID tokens couldn't last an hour. Potentially even up to a week or more. The only problem I see is that if an app only checks whether a token is still valid, rather than checking how long ago it was issued, you could have apps trusting really old tokens. I wouldn't doubt if there are apps out there that would do that. Easy mistake to make. So we probably wouldn't want to make them last forever.

>  I suspect refresh would be the nicest UX

I agree. Even though it doesn't really make sense for obligator's architecture, it's the flow that apps expect. There's precedent for this. obligator implements OIDC dynamic client registration, even though it adds basically nothing. This is done for compatibility reasons.

So I think I'll add refresh tokens. Not sure about when I'll get to this though. What's your timeline, especially if I can give you 1 hour+ ID tokens immediately?

**Comment by anderspitman** [comment]
@btrepp I went ahead and upped LastLogin's ID tokens to 24 hours. That seems like a fairly reasonable value.

**Comment by btrepp** [comment]
24 hours is awesome :) thanks.

With 24 hours being stacks for now, and it's an open source tool. My timeline is anytime before the heat death of the universe. So don't feel obligated (haha) to implement this unless you get the passion too :).
